name: 'Godot - Builder'
author: 'Lorenzo Capalbo <capalbo.lorenzo@tutanota.com>'
description: 'Build your Godot 4 projects'

branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  godot-version:
    description: 'Godot engine version'
    required: true
    default: 'latest'
  target-platform:
    description: 'Export target platform'
    required: true
  export-preset:
    description: 'Export preset name'
    required: true
  project-path:
    description: 'Project folder path'
    required: true
    default: '.'
  export-path:
    description: 'Export output path'
    required: true
    default: 'out/'
  export-name:
    description: 'Export project name'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
