name: 'Godot - Builder'
author: 'Lorenzo Capalbo <capalbo.lorenzo@tutanota.com>'
description: 'Build your Godot 4 projects'

branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  export-preset:
    description: 'The name of the export preset to use for building'
    required: true
  export-name:
    description: 'The name of the output artifact, including its extension'
    required: true
  target-platform:
    description: 'The platform you are planning to target'
    required: true
  engine-version:
    description: 'The version of the Godot engine you are targeting'
    required: false
    default: 'latest'
  export-path:
    description: 'The path where the build should be stored'
    required: false
    default: 'out/'
  export-mode:
    description: 'The export mode, choosen between "debug" and "release"'
    required: false
    default: 'release'
  project-path:
    description: 'The relative path to the project'
    required: false
    default: '.'

runs:
  using: 'node16'
  main: 'dist/index.js'
