name: Image release 💿

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Engine version"
        required: true
        type: string
      latest:
        description: "Latest version"
        required: false
        default: false
        type: boolean

jobs:
  build-release-image:
    name: Build and release image 💿
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push the base image
        if: ${{ inputs.latest }} == false
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            GODOT_VERSION=${{ github.event.inputs.version }}
          file: images/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/godot:${{ github.event.inputs.version }}
      
      - name: Build and push the latest base image
        if: ${{ inputs.latest }} == true
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            GODOT_VERSION=${{ github.event.inputs.version }}
          file: images/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/godot:latest
            ${{ secrets.DOCKERHUB_USER }}/godot:${{ github.event.inputs.version }}
      
      - name: Build and push the linux image variant
        if: ${{ inputs.latest }} == false
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            GODOT_VERSION=${{ github.event.inputs.version }}
          file: images/linux/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/godot:${{ github.event.inputs.version }}-linux
      
      - name: Build and push the latest linux image variant
        if: ${{ inputs.latest }} == true
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            GODOT_VERSION=${{ github.event.inputs.version }}
          file: images/linux/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/godot:latest-linux
            ${{ secrets.DOCKERHUB_USER }}/godot:${{ github.event.inputs.version }}-linux
          
