name: Windows build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          lfs: true

      - name: Build windows artifact
        uses: ./
        with:
          target-platform: 'windows'
          project-path: 'test-project/'
          export-preset: 'Windows Desktop'
          export-name: 'game.exe'
      
      - name: Check for artifact existence
        run: |
          [ -f out/game.exe ]
