name: Test action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: 'Test windows build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          lfs: true
      
      - name: Export for windows
        uses: ./
        with:
          godot-version: 4.0
          target-platform: win
          export-preset: 'Windows Desktop'
          project-path: test/
          export-path: out/windows/game.exe
